steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/mealtracker-ai',
      '--build-arg', 'REACT_APP_VISION_API_ENDPOINT=https://vision.googleapis.com/v1/images:annotate',
      '--build-arg', 'REACT_APP_GOOGLE_CLOUD_API_KEY=$$VISION_API_KEY',
      '.'
    ]
    secretEnv: ['VISION_API_KEY']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mealtracker-ai']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'mealtracker-ai'
      - '--image'
      - 'gcr.io/$PROJECT_ID/mealtracker-ai'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/vision-api-key/versions/latest
      env: 'VISION_API_KEY'

images:
  - 'gcr.io/$PROJECT_ID/mealtracker-ai' 